#:kivy 1.9
#:include piTFT/controls/circle_button.kv
#:include piTFT/controls/thick_bar.kv
#:include piTFT/colors.kv

BoxLayout:
  canvas.before:
    Color:
      rgba: offwhite
    Rectangle:
      pos: self.pos
      size: self.size
  orientation: 'vertical'
  BoxLayout:
    orientation: 'vertical'
    padding: 30
    size_hint_y: 0.66
    
    ThickBar:
      height: 70
      value: 0.2
      bar_color: blue
      
  BoxLayout:
    orientation: 'horizontal'
    padding: 10
    spacing: 10
    pos_hint: {'center_x': 0.5}
    size_hint_y: 0.33

    CircleButton:
      circle_color: green
      text: "FEED"
    CircleButton:
      circle_color: red
      text: "AUTO"
    CircleButton:
      circle_color: yellow
      text: "SET"





#   BoxLayout:
#     orientation: 'vertical'
#     size_hint_y: 0.33
#     ColorBox:
#       id: button_hue
#       size_hint_y: 0.1
#       color: hsv_to_rgb(app.hue, app.saturation, 1.0)
#     LampiToggle:
#       id: button_onoff
#       size_hint_y: 0.90
#       image: 'images/power_icon_light.png'
#       accent_color: hsv_to_rgb(hue_slider.value, saturation_slider.value, 1.0)
#       text: ''
#       state: 'down' if app.lamp_is_on else 'normal'
#       on_state:  app.lamp_is_on = True if self.state == 'down' else False

