#:include piTFT/colors.kv

<ThickBar@Widget>:
    value: 0.5
    max: 1.0
    bar_color: 0, 0.7, 0.2, 1
    background_color: 0.8, 0.8, 0.8, 1

    canvas:
        Color:
            rgba: self.background_color
        Rectangle:
            pos: self.pos
            size: self.size

        Color:
            rgba: self.bar_color
        Rectangle:
            pos: self.pos
            size: (self.width, self.height * (self.value / self.max))